name: video_trimmer
description: A Flutter package for trimming videos. This supports retrieving, trimming, and storage of trimmed video files to the file system.
version: 3.0.5
homepage: https://github.com/sbis04/video_trimmer
publish_to: none

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player:
    git:
      url: https://github.com/Moovency/video_player.git
      ref: 37ee8647419bbcfde88cea33841c199181f5e54a
  ffmpeg_kit_flutter_https_gpl: ^6.0.3
  #A personal commit to make this package work, until the PR is accepted.
  video_thumbnail:
    git:
      url: https://github.com/justsoft/video_thumbnail.git
      ref: 67f7f792370e0d394d323ff7d70e204622a530d4
  path_provider: ^2.1.1
  intl: 0.19.0
  path: ^1.8.3
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_lints: ^5.0.0
  lints: ^5.1.1
